{
  "login": "andhikamaheva",
  "id": 4925655,
  "avatar_url": "https://avatars0.githubusercontent.com/u/4925655?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/andhikamaheva",
  "html_url": "https://github.com/andhikamaheva",
  "followers_url": "https://api.github.com/users/andhikamaheva/followers",
  "following_url": "https://api.github.com/users/andhikamaheva/following{/other_user}",
  "gists_url": "https://api.github.com/users/andhikamaheva/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/andhikamaheva/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/andhikamaheva/subscriptions",
  "organizations_url": "https://api.github.com/users/andhikamaheva/orgs",
  "repos_url": "https://api.github.com/users/andhikamaheva/repos",
  "events_url": "https://api.github.com/users/andhikamaheva/events{/privacy}",
  "received_events_url": "https://api.github.com/users/andhikamaheva/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Andhika Maheva Wicaksono",
  "company": "@Labku ",
  "blog": "https://andhikamaheva.com",
  "location": "Surabaya",
  "email": null,
  "hireable": true,
  "bio": "Currently as Software Engineer and challenge addict, dedicated to solve problems with technology",
  "public_repos": 63,
  "public_gists": 4,
  "followers": 28,
  "following": 12,
  "created_at": "2013-07-03T00:38:44Z",
  "updated_at": "2017-11-27T09:24:01Z"
}